# Generated by Django 5.2.1 on 2025-06-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('party_size', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
