# Generated by Django 5.2.1 on 2025-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
